import os
from barras import*
from fun_newton import menu_newton

def bienvenida():
    os.system("cls")
    barra(100)
    sl(1)
    barra(45)
    print("BIENVENIDO", end="")
    barra(45)
    sl(1)
    barra(100)
    sl(1)
    barra(2)
    espacios(29)
    print("UNIVERSIDAD NACIONAL AUTÓNOMA DE MÉXICO",end="")
    espacios(28)
    barra(2)
    sl(1)
    barra(2)
    espacios(29)
    print("FACULTAD DE ESTUDIOS SUPERIORES ACATLÁN", end="")
    espacios(28) 
    barra(2) 
    sl(1)
    barra(2)
    espacios(38)
    print("MÉTODOS NUMÉRICOS II",end="")
    espacios(38)
    barra(2)
    sl(1)
    barra(2)
    espacios(36)
    print("MÉTODO DE NEWTON-RAPSHON",end="")
    espacios(36)
    barra(2)
    sl(1)
    barra(2)
    espacios(5)
    print("Miembros del equipo:", end="")
    espacios(71)
    barra(2)
    sl(1)
    barra(2)
    espacios(10)
    print("-Álvarez Cortes Kevin Alejandro", end="")
    espacios(55)
    barra(2)
    sl(1)
    barra(2)
    espacios(10)
    print("-Bautista Gaona Luis Eduardo",end="")
    espacios(58)
    barra(2)
    sl(1)
    barra(2)
    espacios(10)
    print("-De la Peña Estrada Valerie Samantha", end="")
    espacios(50)
    barra(2)
    sl(1)
    barra(2)
    espacios(10)
    print("-Ortiz Flores Diana Michelle", end="")
    espacios(58)
    barra(2)
    sl(1)
    barra(100)
    sl(1)
    os.system("pause")
    os.system("cls")

def introduccion():
    os.system("cls")
    barra(100)
    sl(1)
    barra(2)
    espacios(2)
    print("Este programa está diseñado para la resolución de ciertos sistemas de ecuaciones mediante el",end="")
    espacios(2)
    barra(2)
    sl(1)
    barra(2)
    espacios(2)
    print("método de Newton-Rapshon, considerado uno de los mejores métodos para resolver un sistema de",end="");
    espacios(2)
    barra(2)
    sl(1)
    barra(2)
    espacios(2)
    print("ecuaciones, sus principales características son:", end="")
    espacios(46)
    barra(2)
    sl(1)
    barra(2)
    espacios(10)
    print("-Tiene convergencia cuadrática", end="")
    espacios(56)
    barra(2)
    sl(1)
    barra(2)
    espacios(10)
    print("-Es costoso con respecto a la evaluación de funciones", end="")
    espacios(33)
    barra(2)
    sl(1)
    barra(2)
    espacios(10)
    print("-Se necesitan ciertos elementos, como la Matriz Jacobina, Matriz Jacobina Inversa,", end="")
    espacios(4)
    barra(2)
    sl(1)
    barra(2)
    espacios(10)
    print(" X vector, F vector", end="")
    espacios(67)
    barra(2)
    sl(1)
    barra(2)
    espacios(10)
    print("-Se auto corrige", end="")
    espacios(70)
    barra(2)
    sl(1)
    barra(100)
    sl(1)
    os.system("pause")
    os.system("cls")

proceso(0.001)
bienvenida()
introduccion()
menu_newton()